modLoader="javafml"
loaderVersion="[37,)"
license="Academic Free License v3.0"

[[mods]]
modId="vfe"
version="1.0.0"
displayName="Vanilla Food Extensions"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="david, MCreator"

[[dependencies.vfe]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




